import { LocaleType } from "./index";

// if you are adding a new translation, please use PartialLocaleType instead of LocaleType

const en: LocaleType = {
  Symbol: "en",
  Title: 'AI E-commerce Scene Generation - 302.AI',
  Auth: {
    NeedCode: 'Require share code',
    InputCode: 'The creator has enabled verification. Please enter the share code below',
    PlaceHodeer: 'Enter share code here',
    ToolBin: 'Tool is disabled. For more information, please visit',
    ToolDel: 'Tool is deleted. For more information, please visit',
    Submit: 'Submit',
    Remind: 'Remember share code',
    CodeError: 'Invalid code!',
    AccountBin: 'Account is disabled!',
    AccountDel: 'Account is deleted!',
    NetworkError: 'Network error. Please refresh the page and try again!',
  },
  Code: {
    TokenMiss: "This tool has been disabled/removed!", // -10001
    TokenInvalid: "This tool has been disabled/removed!", // -10002
    InternalError: 'Internal error. Please contact customer service!', // -10003
    AccountOut: 'Account is in arrears. Please recharge and try again!', // -10004
    TokenExpired: 'Token expired. Please refresh the page and try again!', // -10005
    TotalOut: 'The total limit for the tool has been reached. Please contact the administrator to recharge!', // -10006
    TodayOut: 'The daily limit for the tool has been reached. Please contact the administrator to recharge!', // -10007
    HourOut: 'This free tool\'s hour quota reached maximum limit', // -10012
    ErrorPrompt: 'Video prompt word violates regulations, please re-enter!', // -10011
  },
  Error: {
    InitError: 'Initialization data error!',
    FetchCancel: 'Request cancelled!',
    FetchError: 'Request error!',
    NetworkError: 'Network error. Please try again later!',
    TokenMiss: 'Invalid token. Please verify and try again!',
    AccountError: 'Account error',
    AccountUnvalid: 'Current account is invalid!',
    InternalError: 'Internal error. Please contact customer service!',
    BalanceOut: 'Account balance insufficent. Please recharge!',
    TokenExpire: 'Current token has expired!',
    TotalCostTip: 'Total limit reminder',
    TotalCostOut: 'The total limit for the tool has been reached!',
    TodayCostTip: 'Daily limit reminder',
    TodayCostOut: 'The daily limit for the tool has been reached!',
    FetchNotSupport: 'Request error, image is too large or format is not supported!'
  },
  System: {
    Notify: 'System Notification',
    Title: 'System Notification',
    Add: 'Add',
    Modify: 'Modify',
    Delete: 'Delete',
    Faild: 'Failed',
    Success: 'Success',
    NotNow: 'Not now',
    Cancel: 'Cancel',
    Start: 'Start',
    Back: 'Back',
    Download: 'Download',
    Confirm: 'Confirm',
    Error: 'Network Error',
    Wait: 'System is busy. Please wait!',
    BalanceOut: 'Account balance is insufficient!',
    Visit: 'Please view',
    Register: 'Please sign up',
    Create: 'to create your own tool',
    Task: 'Task',
    ToLarge: 'The image is too large, currently we do not support image processing for files larger than 10MB.',
    Nosupport: 'Free version does not support this feature',
  },
  Home: {
    Title: 'AI E-commerce Scene Generation',
  },
  About: {
    Title: 'About',
    Name: 'AI E-commerce Scene Generation',
    User: 'This photo tool is created by 302.AI user',
    Create: '',
    Tool: 'which is a platform for generating and sharing AI. 302.AI allows for the one-click generation and sharing of your own AI robot.',
    Model: 'This tool uses the following model',
    AllCost: 'The total limitation of this photo tool is',
    TodayCost: 'The daily limitation of this photo tool is',
    Usage: 'Usage:',
    Record: 'All records of this tool are stored on this machine and will not be uploaded. The user who generated this tool cannot see your records.',
    More: 'For more information, please view:',
    Tip: 'Content generated by AI, for reference only'
  },
  Action: {
    DropIn: 'Click or drag and drop to upload',
    Enlarge: 'Lossless enlargement',
    Enhance: 'Enhance characters',
    Colorize: 'Colorize black and white',
    Break: 'The generation task is in progress, are you sure you want to go back?',
    CreatVideoPrompt: 'Please enter the content you want to generate based on the images',
    WaitImage: 'Task submitted, estimated wait time is about 1 minute',
    WaitVideo: 'Please wait 5-10 minutes',
    CreatImage: 'Generate image',
    CreatVideo: 'Generate video',
    DownloadImage: 'Download image',
    DownloadVideo: 'Download video',
    RegenerateImage: 'Regenerate Image',
    ReGenerateVideo: 'Regenerate Video',
    DownloadImageTip: 'Image generation complete, please download and save it in time!',
    DownloadVideoTip: 'Video generation complete, please download and save it in time!',
    ResultOptions: [
      { label: 'Image', value: 'image', disabled: false },
      { label: 'Video', value: 'video', disabled: false },
    ],
  },
  History: {
    Title: 'History',
    Empty: 'Sorry, no history records!',
    Error: 'Data format error!',
    RollbackSuccess: 'Record rollback success!',
    RollbackFaild: 'Record rollback failed, data abnormality!',
    ClearSuccess: 'All history records have been deleted!',
    RecordType: 'Record type',
    ClearAll: 'Clear all history records',
    ClearAllSure: 'Are you sure you want to clear all history records?',
    Clear: 'Clear',
    NotNow: 'Not now',
    ItemCount: (count: number) => `Total ${count} history records`,
  },
  Example: {
    title: 'TRY AN EXAMPLE',
    action: 'Try with this example',
    demos: [
      {
        title: 'Product Scene',
        desc: 'This tool can intelligently adjust the lighting and visual effects of the product based on different environmental scenes, ensuring that the product can showcase its best state in any background. (Keywords for this case: lunar surface)',
        before: '/images/product-before.jpeg',
        after: '/images/product-after.jpeg',
        action: {
          generateTimes: 0,
          generateType: 'light',
          // 
          maskFile: null,
          prompt: '',
          // 
          productType: 'product',
          productText: 'sports car',
          productFile: null,
          //
          sceneType: 'text',
          sceneText: 'lunar surface',
          sceneFile: null,
          //
          lightType: 'None',
          //
          result: '',
          video: '',
        }
      },
      {
        title: 'Model Scene',
        desc: 'This tool can intelligently adjust the lighting and visual effects of the model based on different environmental scenes, ensuring that the model can showcase its best state in any background. (Keywords for this case: live concert)',
        before: '/images/model-before.jpeg',
        after: '/images/model-after.jpeg',
        action: {
          generateTimes: 0,
          generateType: 'light',
          //
          maskFile: null,
          prompt: '',
          // 
          productType: 'model',
          productText: 'model',
          productFile: null,
          //
          sceneType: 'text',
          sceneText: 'live concert',
          sceneFile: null,
          //
          lightType: 'None',
          //
          result: '',
          video: '',
        }
      },
    ]
  },
  Landing: {
    ProductTitle: 'Product',
    ProductInput: 'Please enter the product name',
    ModelInput: 'Please enter the model\'s characteristics',
    ProductUpload: 'Upload product real shot image',
    ModelUpload: 'Upload model real shot image',
    SceneTitle: 'Scene',
    SceneInput: 'Please enter scene description',
    SceneUpload: 'Upload scene reference image',
    StartGenerate: 'Start Generating',
    ProductOptions: [
      { label: 'Product', value: 'product', disabled: false },
      { label: 'Model', value: 'model', disabled: false },
    ],
    SceneOptions: [
      { label: 'Text', value: 'text', disabled: false },
      { label: 'Image', value: 'image', disabled: false },
    ],
    LightOptions: [
      { label: 'Auto', value: 'None', disabled: false },
      { label: 'Top Light', value: 'Top Light', disabled: false },
      { label: 'Bottom Light', value: 'Bottom Light', disabled: false },
      { label: 'Left Light', value: 'Left Light', disabled: false },
      { label: 'Right Light', value: 'Right Light', disabled: false },
    ],
    RatioOptions: [
      { id: -1, label: 'Origin', value: -1, disabled: false },
      { id: 0, label: 'Customize', value: 0, disabled: false },
      { id: 1, label: '1:1', value: 1 / 1, disabled: false },
      { id: 2, label: '4:3', value: 4 / 3, disabled: false },
      { id: 3, label: '3:4', value: 3 / 4, disabled: false },
      { id: 4, label: '16:9', value: 16 / 9, disabled: false },
      { id: 5, label: '9:16', value: 9 / 16, disabled: false },
    ],
    GenerateOptions: [
      { label: 'Use Original Scene', value: 'light-bg', disabled: false },
      { label: 'Generate Similar Scene', value: 'light', disabled: false },
    ],
  },
  Ratio: {
    Title: 'Set Custom Ratio',
    Customize: 'Customize',
    Width: 'Width',
    Height: 'Height',
    WidthTip: 'Please enter width',
    HeightTip: 'Please enter height',
    Submit: 'Submit',
    Cancel: 'Cancel',
    Tip: 'Aspect ratio limit: 1/4 ~ 4/1',
    Error: 'Unsupported ratio, please modify and try again',
  }
};

export default en;
